name: Build and Deploy Wanderlust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build Backend Image
      run: |
        cd wanderlust-3tier-project
        docker build -t ${{ secrets.DOCKER_USERNAME }}/wanderlust-backend:${{ github.run_number }} -f ./backend/Dockerfile_optimized ./backend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/wanderlust-frontend:${{ github.run_number }} -f ./frontend/Dockerfile_optimized ./frontend
    
    - name: Push Images to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/wanderlust-backend:${{ github.run_number }}
        docker push ${{ secrets.DOCKER_USERNAME }}/wanderlust-frontend:${{ github.run_number }}
    
    - name: Run Trivy vulnerability scanner - Backend
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.DOCKER_USERNAME }}/wanderlust-backend:${{ github.run_number }}
        format: 'sarif'
        output: 'backend-trivy-results.sarif'
        exit-code: 0
    
    - name: Run Trivy vulnerability scanner - Frontend  
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.DOCKER_USERNAME }}/wanderlust-frontend:${{ github.run_number }}
        format: 'sarif'
        output: 'frontend-trivy-results.sarif'
        exit-code: 0
        
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: '.'
