version: "3.8"
services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./backend/data:/data
    ports:
      - "27017:27017"

  backend:
    container_name: backend
    image: devopswithjunaid/wanderlust-backend:${BUILD_NUMBER}
    environment:
      - MONGODB_URI=mongodb://mongo/wanderlust
      - CORS_ORIGIN=http://<REMOTE_SERVER_IP>:8082
    ports:
      - "8081:5000"
    depends_on:
      - mongodb

  frontend:
    container_name: frontend
    image: devopswithjunaid/wanderlust-frontend:${BUILD_NUMBER}
    environment:
      - VITE_API_PATH=http://<REMOTE_SERVER_IP>:8081
    ports:
      - "8082:5173"
    depends_on:
      - backend

volumes:
  data:
